name: Build and deploy

env:
  AZURE_WEBAPP_NAME: httpstatus-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker Build & Push to ACR
        run: |
            docker build . -t ${{ secrets.REGISTRY_URL }}/httpstatus:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_URL }}/httpstatus:${{ github.sha }} 

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          images: ${{ secrets.REGISTRY_URL }}/httpstatus:${{ github.sha }}