name: Build and deploy

env:
  AZURE_WEBAPP_NAME: httpstatus-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    name: Build Docker images for Azure Container Registry and GitHub Container Registry
    environment:
      name: build

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.GH_REGISTRY_URL }}/aaronpowell/httpstatus,${{ secrets.AZURE_REGISTRY_URL }}/aaronpowell/httpstatus
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long,prefix=

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src
          file: src/Teapot.Web/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      #- name: Build Docker images
      #  working-directory: src/Teapot.Web
      #  run: |
      #      docker build -f Dockerfile -t ${{ secrets.AZURE_REGISTRY_URL }}/httpstatus:${{ github.sha }} -t ${{ secrets.GH_REGISTRY_URL }}/httpstatus:${{ github.sha }} ..

      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_URL }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

  #    - name: Publish to ACR
  #      run: docker push ${{ secrets.AZURE_REGISTRY_URL }}/httpstatus:${{ github.sha }}

  #    - name: GPR authentication
  #      uses: azure/docker-login@v1
  #      with:
  #        login-server: ${{ secrets.AZURE_REGISTRY_URL }}
  #        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
  #        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

  #    - name: Publish to GPR
  #      run: docker push ${{ secrets.GH_REGISTRY_URL }}/httpstatus:${{ github.sha }}

  #deploy-azure:
  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Azure authentication
  #      uses: azure/login@v1
  #      with:
  #        client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #    - name: Deploy to Azure WebApp
  #      uses: azure/webapps-deploy@v2
  #      with:
  #        app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #        images: ${{ secrets.AZURE_REGISTRY_URL }}/httpstatus:${{ github.sha }}